[project]
authors = ["andycancado <andycancado@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community"]
description = "Basic Port to Mojo of HammingCode"
name = "hmg_mojo"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
max = ">=24.6.0,<25"

[tasks]
build = "mojo build main.mojo -o hmg_mojo"
start = "magic run build && ./hmg_mojo"
